config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  get 'ui(/:action)', controller: 'ui'
  get 'privacy', to: "front#privacy"
  
  resources :seo_score, only: [:index] 
  get 'results', to: "seo_score#results"
  
  resources :shops, only: [:show, :destroy, :update] do 
    get 'needs_seo_help', to: 'shops#needs_seo_help'
    resources :keywords, module: :shops 
    resources :tests, module: :shops 
    resources :pages, module: :shops do 
      collection do 
        get 'insights', to: 'pages#insights'
      end
      resources :tests, module: :pages
    end
    resource :recurring_application_charge, only: [:show, :destroy, :create], module: :shops do
      post 'create_subscription', to: 'recurring_application_charge#recurring_application_charge'
      collection do
        get :callback
        post :customize
      end
    end
  end
  
  get 'auth/google_oauth2/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  
  get 'select_website', to: 'search_console#select_website'
  get 'downloading_data', to: 'search_console#downloading_data'
  
  resources :charts do 
    collection do 
      get "branded", to: "charts#branded"
      get 'longtail', to: "charts#longtail"
      get 'transactional', to: "charts#transactional"
    end
  end
  
  get 'sign_in', to: "session#new"
  get 'sign_out', to: 'session#destroy'
  resources :session, only: [:create]
  
  namespace :admin do 
    resources :tests 
    resources :shops do 
      collection do 
        get 'delete_everything', to: 'shops#delete_everything'
      end
      get 'reset_gsc', to: 'shops#reset_gsc'
      get 'delete_gsc', to: 'shops#delete_gsc'
      resources :pages, module: :shops do 
        resources :tests, module: :pages
      end
    end
  end
  
  controller :mandatory_webhooks do
    post '/webhooks/shop_redact' => :shop_redact
    post '/webhooks/customers_redact' => :customers_redact
    post '/webhooks/customers_data_request' => :customers_data_request
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/shops/pages/tests_controller.rb
class Admin::Shops::Pages::TestsController < ApplicationController
  def new
    @shop = Shop.find_by slug: params[:shop_id]
    @page = @shop.pages.find_by slug: params[:page_id]
    @tests = @page.tests
    @test = @page.tests.new
    
    @starting_date = Time.current + 3.days
    @ending_date = Time.current + 33.days
    @one_week_before_starting_date = Time.current - 7.days
    @one_week_before_ending_date = Time.current - 1.days
    @two_week_before_starting_date = Time.current - 14.days
    @two_week_before_ending_date = Time.current - 1.days
    @four_week_before_starting_date = Time.current - 30.days
    @four_week_before_ending_date = Time.current - 1.days
    @one_week_after_starting_date = Time.current + 3.days
    @one_week_after_ending_date = Time.current + 10.days
    @two_week_after_starting_date = Time.current + 3.days
    @two_week_after_ending_date = Time.current + 17.days
    @four_week_after_starting_date = Time.current + 3.days
    @four_week_after_ending_date = Time.current + 33.days
    shopify_session = ShopifyAPI::Session.new(domain: @shop.shopify_domain, token: @shop.shopify_token, api_version: '2019-10')
    ShopifyAPI::Base.activate_session(shopify_session)
    if @page.shopify_page_type == "products"
      begin 
        @shopify_page = ShopifyAPI::Product.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
      end
    elsif @page.shopify_page_type == "pages"
      begin 
        @shopify_page = ShopifyAPI::Page.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
      end
    elsif @page.shopify_page_type == "blogs"
      begin 
        @shopify_page = ShopifyAPI::Article.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
        begin 
          @shopify_page = ShopifyAPI::Blog.find(@page.shopify_id)
        rescue ActiveResource::ResourceNotFound
          nil
        end
      end
    elsif @page.shopify_page_type == "collections"
      begin 
        @shopify_page = ShopifyAPI::CustomCollection.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
        begin 
          @shopify_page = ShopifyAPI::SmartCollection.find(@page.shopify_id)
        rescue ActiveResource::ResourceNotFound
          nil
        end
      end
    end
    if @shopify_page != nil
      if @shopify_page.metafields.any?
        @title = @shopify_page.metafields.select { |attribute| attribute.namespace == 'global' && attribute.key == "title_tag" }.first.value
        @meta_description = @shopify_page.metafields.select { |attribute| attribute.namespace == 'global' && attribute.key == "description_tag" }.first.value
      else
        @title = ""
        @meta_description = ""
      end
    end
  end
  
  def show
    @shop = Shop.find_by slug: params[:shop_id]
    @page = @shop.pages.find_by slug: params[:page_id]
    @test = @page.tests.find_by id: params[:id]
  end
  
  def create
    @shop = Shop.find_by slug: params[:shop_id]
    @page = @shop.pages.find_by slug: params[:page_id]
    @test = @page.tests.new(test_params)
    shopify_session = ShopifyAPI::Session.new(domain: @shop.shopify_domain, token: @shop.shopify_token, api_version: '2019-10')
    ShopifyAPI::Base.activate_session(shopify_session)
    if @page.shopify_page_type == "products"
      begin 
        @shopify_page = ShopifyAPI::Product.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
      end
    elsif @page.shopify_page_type == "pages"
      begin 
        @shopify_page = ShopifyAPI::Page.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
      end
    elsif @page.shopify_page_type == "blogs"
      begin 
        @shopify_page = ShopifyAPI::Article.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
        begin 
          @shopify_page = ShopifyAPI::Blog.find(@page.shopify_id)
        rescue ActiveResource::ResourceNotFound
          nil
        end
      end
    elsif @page.shopify_page_type == "collections"
      begin 
        @shopify_page = ShopifyAPI::CustomCollection.find(@page.shopify_id)
      rescue ActiveResource::ResourceNotFound
        nil
        begin 
          @shopify_page = ShopifyAPI::SmartCollection.find(@page.shopify_id)
        rescue ActiveResource::ResourceNotFound
          nil
        end
      end
    end
    respond_to do |format|
      if @shopify_page && @test.save
        @page.update(testing: true)
        title_metafield = ShopifyAPI::Metafield.new(:namespace => "global", :key => "title_tag", :value => @test.title, :value_type => "string")
        desc_metafield = ShopifyAPI::Metafield.new(:namespace => "global", :key => "description_tag", :value => @test.description, :value_type => "string")
        @shopify_page.add_metafield(title_metafield)
        @shopify_page.add_metafield(desc_metafield)
        SearchConsole::GetFirstDataForTestWorker.perform_async(@shop.id, @page.id, @test.id)
        format.html { redirect_to admin_shop_page_test_path(@shop, @page, @test), notice: 'Test was created and we have updated the page title and meta description tags. The results for this test will be updated in 7, 14 and 30 days.' }
        format.json { render :show, status: :created, location: @test }
      else
        if @shopify_page != nil
          @title = @shopify_page.metafields.select { |attribute| attribute.namespace == 'global' && attribute.key == "title_tag" }.first.value
          @meta_description = @shopify_page.metafields.select { |attribute| attribute.namespace == 'global' && attribute.key == "description_tag" }.first.value
        end
        format.html { redirect_to new_admin_shop_page_test_path(@shop, @page), notice: 'Please sync your Google Search Console account to the Shopify account before you start updating SEO titles.' }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @shop = Shop.find_by slug: params[:shop_id]
    @page = @shop.pages.find_by slug: params[:page_id]
    @test = @page.tests.find_by id: params[:id]
    ending_date = Time.current - 1.day
    two_week_after_ending_date = Time.current - 1.days
    four_week_after_ending_date = Time.current - 1.days
    @test.update(is_test_over: true, ending_date: ending_date, two_week_after_ending_date: two_week_after_ending_date, 
      four_week_after_ending_date: four_week_after_ending_date
    )
    redirect_to admin_shop_page_test_path(@shop, @page, @test), notice: 'Test was successfully ended.' 
  end
  
  private
  def test_params
    params.require(:test).permit(:shop_id, :page_id, 
      :one_week_before_starting_date, :one_week_before_ending_date,
      :two_week_before_starting_date, :two_week_before_ending_date, :starting_date,
      :four_week_before_starting_date, :four_week_before_ending_date, 
      :one_week_after_starting_date, :one_week_after_ending_date, 
      :two_week_after_starting_date, :two_week_after_ending_date, 
      :four_week_after_starting_date, :four_week_after_ending_date, 
      :is_test_over, :title, :description, :previous_title, :previous_description, :ending_date, 
      :one_week_before_clicks, :one_week_before_impressions, :one_week_before_ctr, :one_week_before_position, :one_week_after_clicks, :one_week_after_impressions, :one_week_after_ctr, :one_week_after_position, 
      :two_week_before_clicks, :two_week_before_impressions, :two_week_before_ctr, :two_week_before_position, :two_week_after_clicks, :two_week_after_impressions, :two_week_after_ctr, :two_week_after_position, 
      :four_week_before_clicks, :four_week_before_impressions, :four_week_before_ctr, :four_week_before_position, :four_week_after_clicks, :four_week_after_impressions, :four_week_after_ctr, :four_week_after_position, 
      :one_week_result_clicks, :one_week_result_impressions, :one_week_result_ctr, :one_week_result_position, 
      :two_week_result_clicks, :two_week_result_impressions, :two_week_result_ctr, :two_week_result_position, 
      :four_week_result_clicks, :four_week_result_impressions, :four_week_result_ctr, :four_week_result_position)
  end
end

app/controllers/admin/shops/pages_controller.rb
class Admin::Shops::PagesController < ApplicationController
  before_action :require_user
  def show
    @shop = Shop.find_by slug: params[:shop_id]
    @page = @shop.pages.find_by slug: params[:id]
    @tests = @page.tests
    if @page.tests.count == 0
      redirect_to new_admin_shop_page_test_path(@shop, @page) 
    else
      shopify_session = ShopifyAPI::Session.new(domain: @shop.shopify_domain, token: @shop.shopify_token, api_version: '2019-10')
      ShopifyAPI::Base.activate_session(shopify_session)
      if @page.store
        if @page.shopify_page_type == "products"
          begin 
            @shopify_page = ShopifyAPI::Product.find(@page.store.shopify_id)
          rescue ActiveResource::ResourceNotFound
            nil
          end
        elsif @page.shopify_page_type == "pages"
          begin 
            @shopify_page = ShopifyAPI::Page.find(@page.store.shopify_id)
          rescue ActiveResource::ResourceNotFound
            nil
          end
        elsif @page.shopify_page_type == "blogs"
          begin 
            @shopify_page = ShopifyAPI::Article.find(@page.store.shopify_id)
          rescue ActiveResource::ResourceNotFound
            nil
            begin 
              @shopify_page = ShopifyAPI::Blog.find(@page.store.shopify_id)
            rescue ActiveResource::ResourceNotFound
              nil
            end
          end
        elsif @page.shopify_page_type == "collections"
          begin 
            @shopify_page = ShopifyAPI::CustomCollection.find(@page.store.shopify_id)
          rescue ActiveResource::ResourceNotFound
            nil
            begin 
              @shopify_page = ShopifyAPI::SmartCollection.find(@page.store.shopify_id)
            rescue ActiveResource::ResourceNotFound
              nil
            end
          end
        end
      end
      if @shopify_page != nil
        if @shopify_page.metafields.any?
          @title = @shopify_page.metafields.select { |attribute| attribute.namespace == 'global' && attribute.key == "title_tag" }.first.value
          @meta_description = @shopify_page.metafields.select { |attribute| attribute.namespace == 'global' && attribute.key == "description_tag" }.first.value
        else
          @title = ""
          @meta_description = ""
        end
      end
    end
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :require_user
  def index
    @shops = Shop.all
  end
  
  def show 
    @shop = Shop.find_by slug: params[:id]
    @pages = @shop.pages.paginate(page: params[:page], per_page: 50)
    @tests = @shop.tests.first(50)
  end
  
  def delete_everything
    Shops::DeleteAllTablesWorker.perform_async()
    redirect_to admin_shops_path
  end
  
  def reset_gsc
    @shop = Shop.find_by slug: params[:shop_id]
    Shops::DeleteAllPagesWorker.perform_async(@shop.id)
    SearchConsole::GetPagesFirstTimeWorker.perform_in(5.minutes, @shop.id)
    redirect_to admin_shops_path
  end
  
  def delete_gsc
    @shop = Shop.find_by slug: params[:shop_id]
    @shop.update(google_website: nil, google_token: nil, google_refresh_token: nil, expiresat: nil)
    redirect_to admin_shops_path
  end
  
  def destroy
    @shop = Shop.find_by slug: params[:id]
    @shop.destroy
    redirect_to shop_plans_path
  end
  
  private
  def require_admin
    if !current_user.admin?
      flash[:error] = "You are not authorised to do that"
      redirect_to root_path 
    end
  end
end

app/controllers/shops/keywords_controller.rb
class Shops::KeywordsController < ApplicationController
  
  def index
    @shop = Shop.find_by slug: params[:shop_id]
    if params[:sort] == "1_word"
      @viewing = "1 Word Keywords"
      @keywords = @shop.keywords.where(keyword_count: 1).paginate(page: params[:page], per_page: 50)
    elsif params[:sort] == "2_word"
      @viewing = "2 Word Keywords"
      @keywords = @shop.keywords.where(keyword_count: 2).paginate(page: params[:page], per_page: 50)
    elsif params[:sort] == "3_word"
      @viewing = "3 Word Keywords"
      @keywords = @shop.keywords.where(keyword_count: 3).paginate(page: params[:page], per_page: 50)
    elsif params[:sort] == "branded"
      @viewing = "Branded Keywords"
      @keywords = @shop.keywords.where(includes_brand_name: true).paginate(page: params[:page], per_page: 50)
    elsif params[:sort] == "nonbranded"
      @viewing = "Non Branded Keywords"
      @keywords = @shop.keywords.where(includes_brand_name: false).paginate(page: params[:page], per_page: 50)
    else
      @viewing = "4+ Word Keywords"
      @keywords = @shop.keywords.where(keyword_count: 4).paginate(page: params[:page], per_page: 50)
    end
    @tests = @shop.tests
  end
end

app/controllers/shops/pages_controller.rb
class Shops::PagesController < ApplicationController
  
  def index
    @shop = Shop.find_by slug: params[:shop_id]
    if params[:sort] == "pages"
      @viewing = "Other pages"
      @insights = @shop.insights.where(shopify_page_type: "pages").paginate(page: params[:page], per_page: 50)
    elsif params[:sort] == "blogs"
      @viewing = "Blog pages"
      @insights = @shop.insights.where(shopify_page_type: "blogs").paginate(page: params[:page], per_page: 50)
    else
      @viewing = "Product + Collection Pages"
      @insights = @shop.insights.where(shopify_page_type: "products").or(@shop.insights.where(shopify_page_type: "products")).or(@shop.insights.where(shopify_page_type: "frontpage")).paginate(page: params[:page], per_page: 50)
    end
    @tests = @shop.tests
  end
  
  def show
    @shop = Shop.find_by slug: params[:shop_id]
    @page = @shop.pages.find_by slug: params[:id]
    @tests = @page.tests
    redirect_to new_shop_page_test_path(@shop, @page) if @page.tests.count == 0
  end
  
  def insights
    @shop = Shop.find_by slug: params[:shop_id]
    @tests = @shop.tests
    @clicks = @shop.clicks
    #Page.destroy_all
    #Keyword.destroy_all
    #Stat.destroy_all
    #KeywordStat.destroy_all
    #PageStat.destroy_all
    #Click.destroy_all
  end
end

app/controllers/shops/tests_controller.rb
class Shops::TestsController < ApplicationController
  def index
    @shop = Shop.find_by slug: params[:shop_id]
    @tests = @shop.tests
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  
  def update
    @shop = Shop.find_by slug: params[:id]
    respond_to do |format|
      if params[:shop][:brand_name] != "" && @shop.update(shop_params)
        format.html { redirect_to root_path }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { redirect_to root_path  }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def needs_seo_help
    @shop = Shop.find_by slug: params[:shop_id]
    @shop.update(needs_help: false)
    AppMailer.send_shop_needs_help(@shop.shopify_domain).deliver_later
    redirect_to insights_shop_pages_path(@shop), notice: "I'll be in touch with you via email (arjunrajkumars@gmail.com) regardign this ASAP. Thanks! - Arjun"
  end

  private
    def shop_params
      params.require(:shop).permit(:brand_name)
    end
end

app/views/admin/shops/index.html.haml
%p#notice= notice
%h1 Shops
= link_to "Delete Everything", delete_everything_admin_shops_path
%table.table.table-hover.align-items-center.table-borderless
  %thead
    %tr
      %th{:scope => "col"} Shop
      %th{:scope => "col"} Google
      %th{:scope => "col"} Tests
      %th{:scope => "col"} Pages
      %th{:scope => "col"} Clicks
      %th{:scope => "col"} created_at
      %th{:scope => "col"}
      %th{:scope => "col"}
  %tbody
    - @shops.each do |shop|
      %tr.bg-white
        %th{:scope => "row"}
          .media.align-items-center
            .media-body
              = link_to insights_shop_pages_path(shop), { :class=>"" }, nil do
                %span.h6.mb-0
                  = shop.shopify_domain
                  %span.badge.badge-secondary= shop.email
              %span.text-muted.text-small= shop.shopify_token
              ||
              %span.text-muted.text-small= shop.domain
        %td
          .media.align-items-center
            .media-body
              %span.h6.mb-0
                = shop.google_website
                ||
                %span.badge.badge-secondary= shop.google_email
                ||
              %span.text-muted.text-small= shop.google_token
              ||
              %span.text-muted.text-small= shop.google_refresh_token
        %td
          = link_to "#{shop.tests.count}", shop_tests_path(shop), class: "nav-link"
        %td= shop.pages.count
        %td= shop.clicks.count
        %td= fix_time(shop.created_at)
        %td= link_to 'Delete GSC Token', admin_shop_delete_gsc_path(shop), data: { confirm: 'Are you sure?' }
        %td= link_to 'Reset Pages from GSC', admin_shop_reset_gsc_path(shop), data: { confirm: 'Are you sure?' }
        %td= link_to 'Destroy', shop_path(shop), method: :delete, data: { confirm: 'Are you sure?' }
      %tr.table-divider

app/views/admin/shops/show.html.haml
.main-container.bg-white
  - flash.each do |key, value|
    .row.justify-content-center.text-center.mb-3
      .col-12
        .alert.alert-danger.mt-3{:role => "alert"}
          %i.icon-shield
          %span
            = value
  - if @tests.count != 0 && @pages.count != 0
    %section.bg-white.space-sm.pb-0
      .container
        .row.justify-content-center.text-center.section-intro
          .col-12.col-md-8.col-lg-7
            %h1.display-3
              %strong On-page SEO Tests
            %span.lead Boost your organic click-through rates by split testing on-page SEO tags (page titles and meta descriptions)
          %section.bg-white.flush-with-above
            .container
              .row
                .col
                  %table.table.table-borderless.table-hover.align-items-center
                    %thead
                      %tr
                        %th{:scope => "col"} Tests
                        %th{:scope => "col"} Clicks
                        %th{:scope => "col"} Impressions
                        %th{:scope => "col"} CTR
                        %th{:scope => "col"} Position
                    %tbody
                      = render partial: 'shops/pages/tests/test', collection: @tests
                / end of col
              .row.justify-content-center.text-center.section-intro.mt-5.mb-3
                .col-12.col-md-10.col-lg-10.text-center.mb-3
                  %h2.display-5.mb-2
                    %strong Google Search Console Data.
                  %span.mt-2 Below is the last 90 days data from Google Search Console.
              %table.table.table-hover.align-items-center.table-borderless
                %thead
                  %tr
                    %th{:scope => "col"} Page
                    %th{:scope => "col"} Impressions
                    %th{:scope => "col"} Clicks
                    %th{:scope => "col"} CTR
                    %th{:scope => "col"} Position
                %tbody
                  = render partial: 'admin/shops/pages/page', collection: @pages
              = will_paginate @pages
            - if (@shop.plans.last.name == "Free") && ((@shop.created_at + 14.days) > Time.current.to_date)
              .justify-content-center.text-center.mt-3
                .alert.alert-dark{:role => "alert"}
                  You have #{trail_days(@shop)} days left in the free trial. Upgrade to run tests without any interruptions.
          - elsif @tests.count == 0 && @pages.count != 0
            %section.space-md
              .bg-white
                .container
                  .row.justify-content-center.text-center.mt-0
                    .col-sm-6.justify-content-center.text-center.bg-white
                      .mb-4.text-center
                        %h3.h2.mb-2
                          %strong Onboarding Guide
                        .progress
                          .progress-bar.bg-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "75", :role => "progressbar", :style => "width: 75%;"} 75%
                      %span.text-muted.text-center.mb-1 3/4 steps completed
                      %ul.list-group.list-group-flush{:style => "border: 1px solid #fff;"}
                        %li.list-group-item.bg-secondary
                          .d-flex.justify-content-between
                            %div{:style => "text-decoration: line-through;"}
                              %i.icon-check.mr-1.text-green
                              Install BoostCTR
                            %span Completed
                        %li.list-group-item.bg-secondary
                          .d-flex.justify-content-between
                            %div{:style => "text-decoration: line-through;"}
                              %i.icon-check.mr-1.text-green>
                              Connect Search Console (GSC)
                            %span Completed
                        %li.list-group-item.bg-secondary
                          .d-flex.justify-content-between
                            %div{:style => "text-decoration: line-through;"}
                              %i.icon-check.mr-1.text-green>
                              Select Website from GSC
                            %span Completed
                        %li.list-group-item
                          .d-flex.justify-content-between
                            %div
                              %i.icon-circle.mr-1>
                              Start SEO Test
                            %span Ongoing
                  .row.justify-content-center.text-center.section-intro.mt-5.mb-0
                    .col-12.col-md-10.col-lg-10.text-center.mb-3
                      %h2.display-5.mb-2
                        %strong Google Search Console Data.
                      %span.mt-2 Below is the last 90 days data from Google Search Console.
                  %table.table.table-hover.align-items-center.table-borderless
                    %thead
                      %tr
                        %th{:scope => "col"} Page
                        %th{:scope => "col"} Impressions
                        %th{:scope => "col"} Clicks
                        %th{:scope => "col"} CTR
                        %th{:scope => "col"} Position
                    %tbody
                      = render partial: 'admin/shops/pages/page', collection: @pages
                  / end of row
                / end of container
          - elsif @shop.google_website == nil
            %section.bg-white.space-sm.pb-0
              .container
                .row.justify-content-center.text-center.mt-0
                  .col-sm-6.justify-content-center.text-center.bg-white
                    .mb-4.text-center
                      %h3.h2.mb-2
                        %strong Onboarding Guide
                      .progress
                        .progress-bar.bg-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "25", :role => "progressbar", :style => "width: 25%;"} 25%
                    %span.text-muted.text-center.mb-1 1/4 steps completed
                    %ul.list-group.list-group-flush{:style => "border: 1px solid #fff;"}
                      %li.list-group-item.bg-secondary
                        .d-flex.justify-content-between
                          %div{:style => "text-decoration: line-through;"}
                            %i.icon-check.mr-1.text-green
                            Install BoostCTR
                          %span Completed
                      %li.list-group-item
                        .d-flex.justify-content-between
                          %div
                            %i.icon-circle.mr-1>
                            Connect Search Console (GSC)
                          %span Ongoing
                      %li.list-group-item.bg-secondary
                        .d-flex.justify-content-between.text-muted
                          %div{:style => ""}
                            %i.icon-check.mr-1.text-muted>
                            Select Website from GSC
                          %span
                      %li.list-group-item.bg-secondary
                        .d-flex.justify-content-between.text-muted
                          %div{:style => ""}
                            %i.icon-check.mr-1.text-muted>
                            Start SEO Test
                          %span
                    = link_to "Connect Google Search Console", '/auth/google_oauth2' , class: "btn btn-success btn-lg mt-4"
                    %small *We need your permission to access your Google Search Console data, so we can accurately measure the impact of your changes. Please sign out of Google if you want to sign in with a new/different Google Search Consle account and try signing in again.
                - else
                  %section.bg-white.space-lg.pb-0
                    .container
                      .row.justify-content-center.text-center.section-intro.mb-0
                        .col-12.col-md-8.col-lg-7
                          %i.icon-hour-glass.text-yellow.display-4
                          %span.lead.text-left
                            We are
                            %strong downloading the last 90 days of data.
                          %span.lead.text-left
                            This should take ~2-5 minutes to complete.