config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  get 'ui(/:action)', controller: 'ui'
  get 'privacy', to: "front#privacy"
  
  resources :seo_score, only: [:index] 
  get 'results', to: "seo_score#results"
  
  resources :shops, only: [:show, :destroy, :update] do 
    get 'needs_seo_help', to: 'shops#needs_seo_help'
    resources :keywords, module: :shops 
    resources :tests, module: :shops 
    resources :pages, module: :shops do 
      collection do 
        get 'insights', to: 'pages#insights'
      end
      resources :tests, module: :pages
    end
    resource :recurring_application_charge, only: [:show, :destroy, :create], module: :shops do
      post 'create_subscription', to: 'recurring_application_charge#recurring_application_charge'
      collection do
        get :callback
        post :customize
      end
    end
  end
  
  get 'auth/google_oauth2/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  
  get 'select_website', to: 'search_console#select_website'
  get 'downloading_data', to: 'search_console#downloading_data'
  
  resources :charts do 
    collection do 
      get "branded", to: "charts#branded"
      get 'longtail', to: "charts#longtail"
      get 'transactional', to: "charts#transactional"
    end
  end
  
  get 'sign_in', to: "session#new"
  get 'sign_out', to: 'session#destroy'
  resources :session, only: [:create]
  
  namespace :admin do 
    resources :tests 
    resources :shops do 
      collection do 
        get 'delete_everything', to: 'shops#delete_everything'
      end
      get 'reset_gsc', to: 'shops#reset_gsc'
      get 'delete_gsc', to: 'shops#delete_gsc'
      resources :pages, module: :shops do 
        resources :tests, module: :pages
      end
    end
  end
  
  controller :mandatory_webhooks do
    post '/webhooks/shop_redact' => :shop_redact
    post '/webhooks/customers_redact' => :customers_redact
    post '/webhooks/customers_data_request' => :customers_data_request
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.haml
.nav-container
  .bg-white.navbar-light{"data-sticky" => "top"}
    .container
      %nav.navbar.navbar-expand-lg
        = link_to root_path, { :class=>"navbar-brand" }, nil do
          %img.navbar-brand-img{:alt => "BCC", :src => "https://boostctr.s3.ap-south-1.amazonaws.com/logo.png", :style => "max-height: 4.4rem;"}/
        %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
          %i.icon-menu.h4
        #navbarNav.collapse.navbar-collapse.justify-content-between
          %ul.navbar-nav
            %li.nav-item
              = link_to "Home", root_path, class: "nav-link"
            - if @shop.google_website
              - if @shop.tests.count != 0
                %li.nav-item
                  = link_to "SEO Tests", shop_tests_path(@shop), class: "nav-link"
              %li.nav-item
                = link_to "Insights", insights_shop_pages_path(@shop), class: "nav-link"
              %li.nav-item
                = link_to "Plans", shop_recurring_application_charge_path(@shop), class: "nav-link"
              
        / end nav collapse
    / end of container

app/views/shared/_notice.html.haml
.row.justify-content-center.text-center
  .col-12.col-md-9.col-lg-8
    .alert.alert-info{:role => "alert"}
      %span
        = active