config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  get 'ui(/:action)', controller: 'ui'
  get 'privacy', to: "front#privacy"
  
  resources :seo_score, only: [:index] 
  get 'results', to: "seo_score#results"
  
  resources :shops, only: [:show, :destroy, :update] do 
    get 'needs_seo_help', to: 'shops#needs_seo_help'
    resources :keywords, module: :shops 
    resources :tests, module: :shops 
    resources :pages, module: :shops do 
      collection do 
        get 'insights', to: 'pages#insights'
      end
      resources :tests, module: :pages
    end
    resource :recurring_application_charge, only: [:show, :destroy, :create], module: :shops do
      post 'create_subscription', to: 'recurring_application_charge#recurring_application_charge'
      collection do
        get :callback
        post :customize
      end
    end
  end
  
  get 'auth/google_oauth2/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  
  get 'select_website', to: 'search_console#select_website'
  get 'downloading_data', to: 'search_console#downloading_data'
  
  resources :charts do 
    collection do 
      get "branded", to: "charts#branded"
      get 'longtail', to: "charts#longtail"
      get 'transactional', to: "charts#transactional"
    end
  end
  
  get 'sign_in', to: "session#new"
  get 'sign_out', to: 'session#destroy'
  resources :session, only: [:create]
  
  namespace :admin do 
    resources :tests 
    resources :shops do 
      collection do 
        get 'delete_everything', to: 'shops#delete_everything'
      end
      get 'reset_gsc', to: 'shops#reset_gsc'
      get 'delete_gsc', to: 'shops#delete_gsc'
      resources :pages, module: :shops do 
        resources :tests, module: :pages
      end
    end
  end
  
  controller :mandatory_webhooks do
    post '/webhooks/shop_redact' => :shop_redact
    post '/webhooks/customers_redact' => :customers_redact
    post '/webhooks/customers_data_request' => :customers_data_request
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/search_console_controller.rb
require 'google/api_client/client_secrets.rb'
require 'google/apis/webmasters_v3'

class SearchConsoleController < AuthenticatedController
  #before_action :set_shop
  #before_action :load_current_recurring_charge
  
  def select_website
    myshopify_domain = ShopifyAPI::Shop.current.myshopify_domain
    @shop = Shop.find_by shopify_domain: myshopify_domain
    begin
      service = Google::Apis::WebmastersV3::WebmastersService.new
      service.authorization = google_secret(@shop).to_authorization 
      service.authorization.refresh! 
    rescue
      service = nil
    end
    @error = ""
    if service && service.list_sites
      begin
        @all_websites = service.list_sites
      rescue Google::Apis::ClientError => e
        raise e
        @error = e.message
      else
        redirect_to root_path, notice: "Please select an account which has access to your Google Search Console" if @all_websites.site_entry == nil
      end
    else
      redirect_to root_path, notice: "Please select an account which has access to your Google Search Console"
    end
  end
  
  def downloading_data
    myshopify_domain = ShopifyAPI::Shop.current.myshopify_domain
    @shop = Shop.find_by shopify_domain: myshopify_domain
    if params[:selected_website] == ""
      redirect_to select_website_path, notice: "Please select a website from Google Search Console to continue."
    else
      selected_website = params[:selected_website]
      if selected_website
        if selected_website.include? "myshopify.com"
          @shop.update(google_website: selected_website, shopify_domain_google_website_match: true)
        else
          @shop.update(google_website: selected_website, shopify_domain_google_website_match: false)
        end
        SearchConsole::GetPagesFirstTimeWorker.perform_async(@shop.id)
        #add sidekiq batches instead - paid plan when upgraded
        30.times do |i|
          n = i * 20
          Partials::Pages::ListJob.set(wait_until: n.seconds.from_now).perform_later(@shop.id)
        end
      end
      redirect_to root_path
    end
  end
  

  private
  
  def google_secret(shop)
    Google::APIClient::ClientSecrets.new(
      { "web" =>
        { "access_token" => @shop.google_token,
          "refresh_token" => @shop.google_refresh_token,
          "client_id" => Rails.application.credentials.google_key,
          "client_secret" => Rails.application.credentials.google_secret
        }
      })
  end
end

app/views/search_console/downloading_data.html.haml
= render partial: 'shared/header', :locals => { :active => 'Home' }
.main-container.bg-white
  %section.bg-white.space-lg.pb-0
    .container
      .row.justify-content-center.text-center.section-intro.mb-0
        .col-12.col-md-8.col-lg-7
          %i.icon-hour-glass.text-yellow.display-4
          %span.lead.text-left
            We are
            %strong downloading the last 90 days of data
            from Google Search Console.
          %span.lead.text-left
            This should take ~2-5 minutes to complete.

app/views/search_console/select_website.html.haml
= render partial: 'shared/header', :locals => { :active => 'Home' }
.main-container.bg-white
  %section.bg-white.space-lg.pb-0
    .container
      - if notice
        = render partial: 'shared/notice', :locals => { :active => notice }
      .row.justify-content-center.text-center.mt-0
        .col-sm-6.justify-content-center.text-center.bg-white
          .mb-4.text-center
            %h3.h2.mb-2 Onboarding Guide
            .progress
              .progress-bar.bg-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%;"} 60%
          %span.text-muted.text-center.mb-1 3/5 steps completed
          %ul.list-group.list-group-flush{:style => "border: 1px solid #fff;"}
            %li.list-group-item.bg-secondary
              .d-flex.justify-content-between
                %div{:style => "text-decoration: line-through;"}
                  %i.icon-check.mr-1.text-green
                  Install BoostCTR
                %span Completed
            %li.list-group-item.bg-secondary
              .d-flex.justify-content-between
                %div{:style => "text-decoration: line-through;"}
                  %i.icon-check.mr-1.text-green
                  Shop Name
                %span Completed
            %li.list-group-item.bg-secondary
              .d-flex.justify-content-between
                %div{:style => "text-decoration: line-through;"}
                  %i.icon-check.mr-1.text-green>
                  Connect Search Console
                %span Completed
            %li.list-group-item
              .d-flex.justify-content-between
                %div
                  %i.icon-circle.mr-1>
                  Select Website from GSC
                %span Ongoing
            %li.list-group-item.bg-secondary
              .d-flex.justify-content-between.text-muted
                %div{:style => ""}
                  %i.icon-check.mr-1.text-muted>
                  Start SEO Test
                %span
          - if @all_websites.site_entry || @error != ""
            = form_tag downloading_data_path, method: 'get', class: 'mb-4' do
              .row.mt-3
                .col-12
                  .form-group
                    = select_tag :selected_website, options_for_select(@all_websites.site_entry.map {|website| website.site_url}), class: 'form-control mb-0', :prompt => "Select website", :autofocus => true
                    %small.mt-0.text-left
                      *Please select the website associated with #{@shop.shopify_domain}
              %div
                %button.btn.btn-md.btn-success{:type => "submit"} Next