config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  get 'ui(/:action)', controller: 'ui'
  get 'privacy', to: "front#privacy"
  
  resources :seo_score, only: [:index] 
  get 'results', to: "seo_score#results"
  
  resources :shops, only: [:show, :destroy, :update] do 
    get 'needs_seo_help', to: 'shops#needs_seo_help'
    resources :keywords, module: :shops 
    resources :tests, module: :shops 
    resources :pages, module: :shops do 
      collection do 
        get 'insights', to: 'pages#insights'
      end
      resources :tests, module: :pages
    end
    resource :recurring_application_charge, only: [:show, :destroy, :create], module: :shops do
      post 'create_subscription', to: 'recurring_application_charge#recurring_application_charge'
      collection do
        get :callback
        post :customize
      end
    end
  end
  
  get 'auth/google_oauth2/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  
  get 'select_website', to: 'search_console#select_website'
  get 'downloading_data', to: 'search_console#downloading_data'
  
  resources :charts do 
    collection do 
      get "branded", to: "charts#branded"
      get 'longtail', to: "charts#longtail"
      get 'transactional', to: "charts#transactional"
    end
  end
  
  get 'sign_in', to: "session#new"
  get 'sign_out', to: 'session#destroy'
  resources :session, only: [:create]
  
  namespace :admin do 
    resources :tests 
    resources :shops do 
      collection do 
        get 'delete_everything', to: 'shops#delete_everything'
      end
      get 'reset_gsc', to: 'shops#reset_gsc'
      get 'delete_gsc', to: 'shops#delete_gsc'
      resources :pages, module: :shops do 
        resources :tests, module: :pages
      end
    end
  end
  
  controller :mandatory_webhooks do
    post '/webhooks/shop_redact' => :shop_redact
    post '/webhooks/customers_redact' => :customers_redact
    post '/webhooks/customers_data_request' => :customers_data_request
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/seo_score_controller.rb
class SeoScoreController < ApplicationController
  def index
  end
  
  def results
    @keyword = params[:focus_keyword]
    @url = params[:page_url]
    if @keyword && @url && url_is_valid?(@url)
      MarketingTool::ScrapePageWorker.perform_async(@url)
    end
    @score = 0
  end
  
  private
  def url_is_valid?(url)
    url.include? "products"
  end
end

app/views/seo_score/index.html.haml
.main-container{:style => ""}
  %section.bg-dark.space-lg
    %img.bg-image{:alt => "Image", :src => "https://boostctr.s3.ap-south-1.amazonaws.com/graphic-bg-clouds-2.png"}/
    .container
      .row.text-center.justify-content-center.section-intro
        .col-12.col-md-10.col-lg-8
          %h1.display-3 Shopify Product Page SEO Scorer
          %span.lead This tool will help you fix all your SEO errors on your Shopify Products page. It checks if the page passes a few important on-page SEO tests, and gives you recommendations on how to fix them.
       
      .row.no-gutters.justify-content-center
        = form_with url: results_url, local: true, method: :get, html: { class: "text-left col-lg-8" } do |form|
          .form-group
            %label{:for => "Enter focus keyword"}
              Enter focus keyword
              %span.text-red *
            = form.text_field :focus_keyword, placeholder: "Enter focus keyword", class: 'input form-control m-b-md', autofocus: true
          .form-group
            %label{:for => "Enter page URL"} 
              Enter the Shopify product page URL
              %span.text-red *
            = form.text_field :page_url, placeholder: "Enter page URL", data: { behavior: "autocomplete" }, class: "form-control form-control-lg"
          .text-center.mt-3
            %button.btn.btn-lg.btn-primary{:type => "submit"} Get Product Page Score

app/views/seo_score/results.html.haml
.main-container{:style => ""}
  %section.bg-dark.space-lg.pt-5
    %img.bg-image{:alt => "Image", :src => "https://boostctr.s3.ap-south-1.amazonaws.com/graphic-bg-clouds-2.png"}/
    .container
      .row
        .col-md-8
          .card.card-sm
            .card-header.d-flex.bg-secondary.justify-content-between.align-items-center
              %div
                %span.mb-1{:style => ""}
                  %h6
                    %strong Keyword:
                    = @keyword
                %br/
                %span{:style => ""}
                  %h6
                    %strong URL:
                    = @url
              